// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.12.4
// source: proto/dvault/v1/dvault.proto

package dvaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username        string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (x *GetVaultRequest) Reset() {
	*x = GetVaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dvault_v1_dvault_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultRequest) ProtoMessage() {}

func (x *GetVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dvault_v1_dvault_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultRequest.ProtoReflect.Descriptor instead.
func (*GetVaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_dvault_v1_dvault_proto_rawDescGZIP(), []int{0}
}

func (x *GetVaultRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetVaultRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type GetVaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedData []byte `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Version       uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     uint64 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *GetVaultResponse) Reset() {
	*x = GetVaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dvault_v1_dvault_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultResponse) ProtoMessage() {}

func (x *GetVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dvault_v1_dvault_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultResponse.ProtoReflect.Descriptor instead.
func (*GetVaultResponse) Descriptor() ([]byte, []int) {
	return file_proto_dvault_v1_dvault_proto_rawDescGZIP(), []int{1}
}

func (x *GetVaultResponse) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *GetVaultResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetVaultResponse) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateVaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username        string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	EncryptedData   []byte `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
}

func (x *UpdateVaultRequest) Reset() {
	*x = UpdateVaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dvault_v1_dvault_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultRequest) ProtoMessage() {}

func (x *UpdateVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dvault_v1_dvault_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVaultRequest.ProtoReflect.Descriptor instead.
func (*UpdateVaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_dvault_v1_dvault_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVaultRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateVaultRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *UpdateVaultRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

type UpdateVaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (x *UpdateVaultResponse) Reset() {
	*x = UpdateVaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dvault_v1_dvault_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultResponse) ProtoMessage() {}

func (x *UpdateVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dvault_v1_dvault_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVaultResponse.ProtoReflect.Descriptor instead.
func (*UpdateVaultResponse) Descriptor() ([]byte, []int) {
	return file_proto_dvault_v1_dvault_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateVaultResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_proto_dvault_v1_dvault_proto protoreflect.FileDescriptor

var file_proto_dvault_v1_dvault_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x72, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x32, 0xa2, 0x01, 0x0a, 0x0d, 0x44, 0x56, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x2e, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1d,
	0x2e, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x74, 0x73, 0x2f, 0x64, 0x2d, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dvault_v1_dvault_proto_rawDescOnce sync.Once
	file_proto_dvault_v1_dvault_proto_rawDescData = file_proto_dvault_v1_dvault_proto_rawDesc
)

func file_proto_dvault_v1_dvault_proto_rawDescGZIP() []byte {
	file_proto_dvault_v1_dvault_proto_rawDescOnce.Do(func() {
		file_proto_dvault_v1_dvault_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dvault_v1_dvault_proto_rawDescData)
	})
	return file_proto_dvault_v1_dvault_proto_rawDescData
}

var file_proto_dvault_v1_dvault_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dvault_v1_dvault_proto_goTypes = []interface{}{
	(*GetVaultRequest)(nil),     // 0: dvault.v1.GetVaultRequest
	(*GetVaultResponse)(nil),    // 1: dvault.v1.GetVaultResponse
	(*UpdateVaultRequest)(nil),  // 2: dvault.v1.UpdateVaultRequest
	(*UpdateVaultResponse)(nil), // 3: dvault.v1.UpdateVaultResponse
}
var file_proto_dvault_v1_dvault_proto_depIdxs = []int32{
	0, // 0: dvault.v1.DVaultService.GetVault:input_type -> dvault.v1.GetVaultRequest
	2, // 1: dvault.v1.DVaultService.UpdateVault:input_type -> dvault.v1.UpdateVaultRequest
	1, // 2: dvault.v1.DVaultService.GetVault:output_type -> dvault.v1.GetVaultResponse
	3, // 3: dvault.v1.DVaultService.UpdateVault:output_type -> dvault.v1.UpdateVaultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dvault_v1_dvault_proto_init() }
func file_proto_dvault_v1_dvault_proto_init() {
	if File_proto_dvault_v1_dvault_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dvault_v1_dvault_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dvault_v1_dvault_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dvault_v1_dvault_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dvault_v1_dvault_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dvault_v1_dvault_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dvault_v1_dvault_proto_goTypes,
		DependencyIndexes: file_proto_dvault_v1_dvault_proto_depIdxs,
		MessageInfos:      file_proto_dvault_v1_dvault_proto_msgTypes,
	}.Build()
	File_proto_dvault_v1_dvault_proto = out.File
	file_proto_dvault_v1_dvault_proto_rawDesc = nil
	file_proto_dvault_v1_dvault_proto_goTypes = nil
	file_proto_dvault_v1_dvault_proto_depIdxs = nil
}
