name: notjustdex_web
description: NotJustDex web app
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.6.0
  notjustdex_identity_kernel:
    path: ../../packages/identity_kernel
  notjustdex_design_system:
    path: ../../packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.8

flutter:
  uses-material-design: true
