name: notjustdex_design_system
description: NotJustDex design system
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.8
