// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dvault/v1/dvault.proto

package dvaultv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/notjustdex/d-vault/proto/dvault/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DVaultServiceName is the fully-qualified name of the DVaultService service.
	DVaultServiceName = "dvault.v1.DVaultService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DVaultServiceGetVaultProcedure is the fully-qualified name of the DVaultService's GetVault RPC.
	DVaultServiceGetVaultProcedure = "/dvault.v1.DVaultService/GetVault"
	// DVaultServiceUpdateVaultProcedure is the fully-qualified name of the DVaultService's UpdateVault
	// RPC.
	DVaultServiceUpdateVaultProcedure = "/dvault.v1.DVaultService/UpdateVault"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	dVaultServiceServiceDescriptor           = v1.File_proto_dvault_v1_dvault_proto.Services().ByName("DVaultService")
	dVaultServiceGetVaultMethodDescriptor    = dVaultServiceServiceDescriptor.Methods().ByName("GetVault")
	dVaultServiceUpdateVaultMethodDescriptor = dVaultServiceServiceDescriptor.Methods().ByName("UpdateVault")
)

// DVaultServiceClient is a client for the dvault.v1.DVaultService service.
type DVaultServiceClient interface {
	GetVault(context.Context, *connect.Request[v1.GetVaultRequest]) (*connect.Response[v1.GetVaultResponse], error)
	UpdateVault(context.Context, *connect.Request[v1.UpdateVaultRequest]) (*connect.Response[v1.UpdateVaultResponse], error)
}

// NewDVaultServiceClient constructs a client for the dvault.v1.DVaultService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDVaultServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DVaultServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dVaultServiceClient{
		getVault: connect.NewClient[v1.GetVaultRequest, v1.GetVaultResponse](
			httpClient,
			baseURL+DVaultServiceGetVaultProcedure,
			connect.WithSchema(dVaultServiceGetVaultMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateVault: connect.NewClient[v1.UpdateVaultRequest, v1.UpdateVaultResponse](
			httpClient,
			baseURL+DVaultServiceUpdateVaultProcedure,
			connect.WithSchema(dVaultServiceUpdateVaultMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// dVaultServiceClient implements DVaultServiceClient.
type dVaultServiceClient struct {
	getVault    *connect.Client[v1.GetVaultRequest, v1.GetVaultResponse]
	updateVault *connect.Client[v1.UpdateVaultRequest, v1.UpdateVaultResponse]
}

// GetVault calls dvault.v1.DVaultService.GetVault.
func (c *dVaultServiceClient) GetVault(ctx context.Context, req *connect.Request[v1.GetVaultRequest]) (*connect.Response[v1.GetVaultResponse], error) {
	return c.getVault.CallUnary(ctx, req)
}

// UpdateVault calls dvault.v1.DVaultService.UpdateVault.
func (c *dVaultServiceClient) UpdateVault(ctx context.Context, req *connect.Request[v1.UpdateVaultRequest]) (*connect.Response[v1.UpdateVaultResponse], error) {
	return c.updateVault.CallUnary(ctx, req)
}

// DVaultServiceHandler is an implementation of the dvault.v1.DVaultService service.
type DVaultServiceHandler interface {
	GetVault(context.Context, *connect.Request[v1.GetVaultRequest]) (*connect.Response[v1.GetVaultResponse], error)
	UpdateVault(context.Context, *connect.Request[v1.UpdateVaultRequest]) (*connect.Response[v1.UpdateVaultResponse], error)
}

// NewDVaultServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDVaultServiceHandler(svc DVaultServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dVaultServiceGetVaultHandler := connect.NewUnaryHandler(
		DVaultServiceGetVaultProcedure,
		svc.GetVault,
		connect.WithSchema(dVaultServiceGetVaultMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	dVaultServiceUpdateVaultHandler := connect.NewUnaryHandler(
		DVaultServiceUpdateVaultProcedure,
		svc.UpdateVault,
		connect.WithSchema(dVaultServiceUpdateVaultMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/dvault.v1.DVaultService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DVaultServiceGetVaultProcedure:
			dVaultServiceGetVaultHandler.ServeHTTP(w, r)
		case DVaultServiceUpdateVaultProcedure:
			dVaultServiceUpdateVaultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDVaultServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDVaultServiceHandler struct{}

func (UnimplementedDVaultServiceHandler) GetVault(context.Context, *connect.Request[v1.GetVaultRequest]) (*connect.Response[v1.GetVaultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dvault.v1.DVaultService.GetVault is not implemented"))
}

func (UnimplementedDVaultServiceHandler) UpdateVault(context.Context, *connect.Request[v1.UpdateVaultRequest]) (*connect.Response[v1.UpdateVaultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dvault.v1.DVaultService.UpdateVault is not implemented"))
}
